// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlwMyrmn-yZ4q9_Yk65AdzsYbcx0P3Zn4',
    appId: '1:832807880844:web:38f061dd7d9441ffa8d3a9',
    messagingSenderId: '832807880844',
    projectId: 'ren-kitahack-2024',
    authDomain: 'ren-kitahack-2024.firebaseapp.com',
    storageBucket: 'ren-kitahack-2024.appspot.com',
    measurementId: 'G-6VBH3ZEHJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKcaBpkZ69HuLps-s6u2Byy6zToxQ6w8',
    appId: '1:832807880844:android:962b101cf94b3676a8d3a9',
    messagingSenderId: '832807880844',
    projectId: 'ren-kitahack-2024',
    storageBucket: 'ren-kitahack-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfDR3XWG6IfkXNDC5mIpg4qfofgoOfbRk',
    appId: '1:832807880844:ios:0824301baa07738da8d3a9',
    messagingSenderId: '832807880844',
    projectId: 'ren-kitahack-2024',
    storageBucket: 'ren-kitahack-2024.appspot.com',
    iosBundleId: 'com.example.ren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfDR3XWG6IfkXNDC5mIpg4qfofgoOfbRk',
    appId: '1:832807880844:ios:0b012f00be741e45a8d3a9',
    messagingSenderId: '832807880844',
    projectId: 'ren-kitahack-2024',
    storageBucket: 'ren-kitahack-2024.appspot.com',
    iosBundleId: 'com.example.ren.RunnerTests',
  );
}
